### ISSUE TITLE
Update the tutorial ?

### ISSUE THREAD

**Issue by jajoe** [abhisheksoni27/machine-learning-with-js#2]
Hello,

Thx for your tuto on Hackernoon. However the code isn't up to date. You use "const knn = new KNN()", and it doesn't work with the current version of ml-knn,
Can you update the code of the tutorial please ?

Thx in advance,

Jajoe

**Comment by abhisheksoni27** [comment]
I updated the code yesterday. Can you Pull upstream and try again?

**Comment by jajoe** [comment]
Oki thx, it works with this repo. 

However the code in https://gist.github.com/abhisheksoni27/ac2b214533eaaf31e78794df39715b68#file-knn-1-js for example hasn't change, so the code showed in the tutorial doesn't work.

**Comment by abhisheksoni27** [comment]
Okay, thanks :laughing:  

I updated the gists.

**Comment by maasencioh** [comment]
thanks :+1:

**Comment by abhisheksoni27** [comment]
@maasencioh :+1:
