### ISSUE TITLE
it can’t find the row values

### ISSUE THREAD

**Issue by senphu** [abhisheksoni27/machine-learning-with-js#3]
https://github.com/abhisheksoni27/machine-learning-with-js/blob/c25d65b4ef26f48a5936524ee63211d5048a936d/linear-regression/index.js#L49

should be:
```
csvData.forEach((row) => {
X.push(f(row.radio));
y.push(f(row.sales));
});
```

**Comment by abhisheksoni27** [comment]
That's strange. It's working at my end, without any changes. 

Can you post the header of `advertising.csv`? (Open the file, copy the first line you see, and paste it here.)

**Comment by ColinRCasto** [comment]
,TV,radio,newspaper,sales
 Heres the first line

**Comment by ColinRCasto** [comment]
just realized the problem, capitalized radio and sales in the .CSV and its working

**Comment by abhisheksoni27** [comment]
There you go! :tada:
